name: Action Sample

on:
  push:
    brunch:
      - master
    workflow_dispach:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Hello World!"